import os

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./mentor_bot.db")

CRM_CLIENT_ID = os.getenv("CRM_CLIENT_ID")
CRM_CLIENT_SECRET = os.getenv("CRM_CLIENT_SECRET")
CRM_AUTH_CODE = os.getenv("CRM_AUTH_CODE")
CRM_SUBDOMAIN = os.getenv("CRM_SUBDOMAIN")
CRM_REDIRECT_URL = "https://ya.ru"
# Пайплайн
CRM_PIPELINE = 9395722
# Ожидаем тест
CRM_TEST_STATUS = 75253982
# Тест в процессе
CRM_TEST_IS_IN_PROGRESS_STATUS = 82881498
# Ожидаем визитку
CRM_VISIT_CARD_STATUS = 82059746
# Визитка отправлена
CRM_VISIT_CARD_IS_SENT_STATUS = 82059750
# Ожидаем тестовое
CRM_TASK_STATUS = 76914298
# Тестовое отправлено наставнику
CRM_TASK_IS_SENT_STATUS = 76914306
# Наставник отклонил
CRM_TASK_IS_DISAPPROVED_STATUS = 81677538
# Наставник принял
CRM_TASK_IS_APPROVED_STATUS = 81677542
# Наставник отложил (сомневается)
CRM_TASK_IS_POSTPONED_STATUS = 87071570

SUPPORT_CONTACT_LINK = "https://t.me/Pokolenez_bot"

DEFAULT_STUDENT_ANKETA_FILENAME = "anketa.pdf"

# API CHAT
CRM_CHAT_CHANNEL_ID = os.getenv("CRM_CHAT_CHANNEL_ID")
CRM_CHAT_CHANNEL_SECRET = os.getenv("CRM_CHAT_CHANNEL_SECRET")
CRM_CHAT_BOT_NAME = os.getenv("CRM_CHAT_BOT_NAME")

# Education pipeline (kicked/banned member flow)
CRM_EDUCATION_PIPELINE = 10726418

# Homework flow
CRM_HOMEWORK_PIPELINE = 10726418
CRM_HW_ASSIGNED_STATUS = "84497006"
CRM_HW_SUBMITTED_STATUS = "84497010"
CRM_HW_EDIT_STATUS = "84880014"
CRM_HW_FOR_MENTOR_STATUS = "84880018"
CRM_HW_APPROVED_STATUS = "84880022"
CRM_HW_EDIT_FROM_MENTOR_STATUS = "84944198"

# Survey pipeline
CRM_SURVEY_PIPELINE = 10726658
